### ISSUE TITLE
no such file or directory: /usr/local/bin/_ash_log

### ISSUE THREAD

**Issue by cmicat** [barabo/advanced-shell-history#2]
## Expected Behavior
I am using zsh with advanced-shell-history python version, after `source /usr/local/lib/advanced_shell_history/sh/zsh`, I should be able to use advanced-shell-history directly.

## Current Behavior
zsh tells me in start up: no such file or directory: /usr/local/bin/_ash_log

## Possible Solution
The problem is that the python version use _ash_log.py instead of _ash_log. We can fix it use a simple symbol link. It should be added to the make file.
```
ln -s /usr/local/bin/ash_query.py /usr/local/bin/ash_query
ln -s /usr/local/bin/_ash_log.py /usr/local/bin/_ash_log
```

## Context (Environment)
Mac OS X 10.12.6
advanced shell history build from master branch (5ce11d2ec3e96bf9bf4f527a48c8717d29a1a762), I am using the python version.
    zsh 5.2 (x86_64-apple-darwin16.0)

**Comment by barabo** [comment]
I've fixed this bug in the latest version.  The problem was that the `common` shell code was expecting the `ASH_LOG_BIN` variable to be defined or it would attempt to set it using the C++ logger.  Since the C++ logger didn't exist, it didn't know to also try the python logger.
