### ISSUE TITLE
Is there a good way to import existing .bash_history to db?

### ISSUE THREAD

**Issue by pspdx** [barabo/advanced-shell-history#7]

**Comment by barabo** [comment]
It depends on the format of the existing history file.  The default bash format does not include the timestamp of the command, only the sequence number - so the start time of the command is typically lost.  It's also very difficult to know what the current working directory is for many different reasons.

In short, there is no good way and there is probably not _any_ way to do it correctly.

**Comment by pspdx** [comment]
Get it. Thanks.
