### ISSUE TITLE
ctrl-c not works after used advanced_shell_history in zsh [Ubuntu16.04]

### ISSUE THREAD

**Issue by pspdx** [barabo/advanced-shell-history#8]
After added these lines into my ~/.zshrc, ctrl-c not works in zsh.

source /usr/local/etc/advanced-shell-history/config                              
export ASH_CFG_SYSTEM_QUERY_FILE                                                 
source /usr/local/lib/advanced_shell_history/sh/zsh

**Comment by barabo** [comment]
Sorry to hear you're having problems.  A couple of questions to clarify, first.

Does everything in the shell _except_ Ctrl-C work?

Does this happen every time you start a zsh shell?

Does typing 'reset' restore Ctrl-C for you?

Are you certain that /usr/local/etc/advanced-shell-history/config exists?  How about the file referenced by $ASH_CFG_SYSTEM_QUERY_FILE?

**Comment by pspdx** [comment]
Sorry to hear you're having problems. A couple of questions to clarify, first.
**This tool works well in bash.**

Does everything in the shell except Ctrl-C work?
**Yes.**

Does this happen every time you start a zsh shell?
**Yes.**

Does typing 'reset' restore Ctrl-C for you?
**Still not work after reset terminal.**

Are you certain that /usr/local/etc/advanced-shell-history/config exists? How about the file referenced by $ASH_CFG_SYSTEM_QUERY_FILE?
**➜  advanced-shell-history git:(master) ls /usr/local/etc/advanced-shell-history/config
/usr/local/etc/advanced-shell-history/config
➜  advanced-shell-history git:(master) echo $ASH_CFG_SYSTEM_QUERY_FILE
/usr/local/etc/advanced-shell-history/queries
➜  advanced-shell-history git:(master)** 

I can saw this when zsh startup:

__ash_end_session () {
	[[ "${ASH:-0}" = "0" ]] && __ash_info __ash_end_session && return
	__ash_log "${@}"
	${ASH_LOG_BIN} --end_session --exit ${1}
}
__ash_log () {
	[[ "${ASH:-0}" = "0" ]] && __ash_info __ash_log && return
	if [[ "${ASH_SKIP:-1}" = "1" ]]
	then
		ASH_SKIP=0 
		return
	fi
	local no start end cmd rval="${1}"  && shift
	read -r no start end cmd <<< "$( __ash_last_command )"
	local pipes="$( sed -e 's: :_:g' <<< "${@}" )" 
	${ASH_LOG_BIN} -e ${rval:-0} -s ${start:-0} -f ${end:-0} -n ${no:-0} -p "${pipes:-0}" -c "${cmd:-UNKNOWN}"
}
Advanced Shell History enabled: session 40                                                                                                                                                                                                                                      
➜  ~

**Comment by pspdx** [comment]
Sent my pull request.
